
default: &default
  adapter: postgresql
  encoding: unicode
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails6_playground_development
  username: rails
  password: rails123

test:
  <<: *default
  database: rails6_playground_test
  username: rails
  password: rails123

# Read http://guides.rubyonrails.org/configuring.html#configuring-a-database
# On Heroku and other platform providers, you may have a full connection URL.
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#   production:
#     url: <%= ENV['DATABASE_URL'] %>

REAL_production:
  <<: *default
  database: rails6_playground_production
  username: rails6_playground
  password: <%= ENV['RAILS6_PLAYGROUND_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: rails6_playground_development
  username: rails
  password: rails123
